"""gmag_webui — the HamSCI magnetometer real-time dashboard, packaged as a
NON-contract catalog component (the ka9q-web shape).

gmag_webui (HamSCI/gmag_webui; Jack Conti + Dave Witten) is a static
single-page app served by a ~60-line Deno static server.  The BROWSER
connects straight to mag-usb's WebSocket feed (``ws://<host>:8765``, which
mag-recorder runs on loopback); Deno is not in the data path.  It has no
radiod binding, instances, or data products, so the client contract's
inventory/validate surfaces would be empty shims — it is a catalog
``server`` with ``contract = ""`` instead, like ka9q-web, and still gets a
checkout under /opt/git/sigmond/, a SHA in versions/manifests, topology
enable/disable, and dormancy with mag-recorder.

What sigmond owns here (and upstream does NOT): the Deno binary (pinned
release, sha256-verified, no ``curl | sh``), the ``.env``, the systemd unit
(dedicated user, Restart=always, NoNewPrivileges), and the update path.
Upstream's ``deploy/gmag-webui-update.timer`` (a 5-minute ``git reset
--hard origin`` + restart) is NEVER installed: it would move a blessed
checkout behind smd's back.  ``smd update`` pulls; the operator restarts.

Pure helpers live here so they are unit-testable; the recipe that touches
the host (clone, download, unzip, unit install) is ``bin/smd``
``_install_gmag_webui_native``.
"""
from __future__ import annotations

import hashlib
from pathlib import Path

COMPONENT   = "gmag-webui"
CHECKOUT    = Path("/opt/git/sigmond") / COMPONENT
SERVICE     = "gmag-webui.service"
UNIT_PATH   = Path("/etc/systemd/system") / SERVICE
SERVICE_USER = "gmagweb"
HOST        = "0.0.0.0"
# 8000 = timestd web-api, 8081 = ka9q-web (RAC VM-web), 8765 = mag-usb WS.
PORT        = 8082
DENO_DIR    = Path("/var/lib/gmag-webui/deno")     # module cache, owned by SERVICE_USER

# Deno is not packaged by Debian.  Pin a release; the recipe downloads the
# zip once, verifies it, and installs under DENO_ROOT/<version>/ with a
# stable /usr/local/bin/deno symlink.  Bump both constants together; the
# sha256 is the published deno-x86_64-unknown-linux-gnu.zip.sha256sum.
DENO_VERSION = "v2.9.5"
DENO_SHA256  = "8b010a3b1a4a0188a67cdb8a7a27348b2a501af78aec7fc74f2ace167368d530"
DENO_ASSET   = "deno-x86_64-unknown-linux-gnu.zip"
DENO_ROOT    = Path("/usr/local/lib/deno")
DENO_BIN     = Path("/usr/local/bin/deno")
DENO_CACHE_DIR = Path("/var/cache/sigmond")

# Upstream vendors Font Awesome as a zip the operator must unzip (README).
FONTAWESOME_ZIP = "vendor/fontawesome-free-7.1.0-web.zip"


def deno_zip_url(version: str = DENO_VERSION) -> str:
    return (f"https://github.com/denoland/deno/releases/download/"
            f"{version}/{DENO_ASSET}")


def deno_install_dir(version: str = DENO_VERSION) -> Path:
    return DENO_ROOT / version


def verify_sha256(path: Path, expected: str) -> bool:
    """True iff ``path`` exists and its sha256 equals ``expected``."""
    try:
        h = hashlib.sha256()
        with open(path, "rb") as fh:
            for chunk in iter(lambda: fh.read(1 << 20), b""):
                h.update(chunk)
    except OSError:
        return False
    return h.hexdigest() == expected.lower()


def render_env(host: str = HOST, port: int = PORT) -> str:
    """The repo-root ``.env`` upstream's ts/main.ts reads (HOST/PORT)."""
    return f'HOST="{host}"\nPORT="{port}"\n'


def render_unit(*, checkout: Path = CHECKOUT, deno_bin: Path = DENO_BIN,
                user: str = SERVICE_USER, deno_dir: Path = DENO_DIR,
                port: int = PORT) -> str:
    return f"""\
# {SERVICE} — generated by `smd install gmag-webui`; do not hand-edit
# (re-run the install to regenerate).  Serves the HamSCI magnetometer
# dashboard on :{port}; the browser connects to mag-usb's WebSocket feed
# (mag-recorder, ws://127.0.0.1:8765) directly — Deno is not in the data path.
# --no-lock: Deno 2 would otherwise write deno.lock beside deno.json inside
# the read-only, sigmond-owned checkout (EROFS under ProtectSystem=strict).
# Upstream's gmag-webui-update.timer is deliberately NOT installed: smd
# update owns the checkout.

[Unit]
Description=HamSCI magnetometer real-time dashboard (gmag_webui, port {port})
Documentation=https://github.com/HamSCI/gmag_webui
After=network-online.target mag-recorder.service
Wants=network-online.target

[Service]
Type=simple
User={user}
Group={user}
WorkingDirectory={checkout}
EnvironmentFile={checkout}/.env
Environment=DENO_DIR={deno_dir}
Environment=DENO_NO_UPDATE_CHECK=1
ExecStart={deno_bin} run --no-lock --allow-net --allow-read={checkout} --allow-env ts/main.ts
Restart=always
RestartSec=3
NoNewPrivileges=true
ProtectSystem=strict
ReadWritePaths={deno_dir}
PrivateTmp=true

[Install]
WantedBy=multi-user.target
"""


def plan_lines(*, checkout: Path = CHECKOUT) -> list:
    """What the recipe will do — printed verbatim by --dry-run and as the
    heading of a real run, so the two never drift."""
    return [
        f"clone/pull {COMPONENT} -> {checkout}",
        f"deno {DENO_VERSION}: download {DENO_ASSET} (sha256-verified) -> "
        f"{deno_install_dir()} ; symlink {DENO_BIN}",
        f"unzip {FONTAWESOME_ZIP} in place; pre-warm the module cache in {DENO_DIR}",
        f"write {checkout}/.env (HOST={HOST} PORT={PORT}); user {SERVICE_USER}",
        f"write {UNIT_PATH} (ours; upstream's auto-update timer is NOT installed)",
    ]
